#                       _______            __                                                         #
#                      /       \          /  |                                                        #
#                      $$$$$$$  | ______  $$ |  ______   _______    _______   ______                  #
#                      $$ |__$$ |/      \ $$ | /      \ /       \  /       | /      \                 #
#                      $$    $$< $$$$$$  |$$ | $$$$$$  |$$$$$$$  |/$$$$$$$/ /$$$$$$  |                #
#                      $$$$$$$  |/    $$ |$$ | /    $$ |$$ |  $$ |$$ |      $$    $$ |                #
#                      $$ |__$$ /$$$$$$$ |$$ |/$$$$$$$ |$$ |  $$ |$$ \_____ $$$$$$$$/                 #
#                      $$    $$/$$    $$ |$$ |$$    $$ |$$ |  $$ |$$       |$$       |                #
#        ________      $$$$$$$/  $$$$$$$/ $$/  $$$$$$$/ $$/  __$/  $$__$$$/  $$$$$$$/                 #
#       /        |                                          /  |    /  |                              #
#       $$$$$$$$/_____    ______   _____  ____    ______   _$$ |_  _$$ |_     ______    ______        #
#       $$ |__ /      \  /      \ /     \/    \  /      \ / $$   |/ $$   |   /      \  /      \       #
#       $$    /$$$$$$  |/$$$$$$  |$$$$$$ $$$$  | $$$$$$  |$$$$$$/ $$$$$$/   /$$$$$$  |/$$$$$$  |      #
#       $$$$$/$$ |  $$ |$$ |  $$/ $$ | $$ | $$ | /    $$ |  $$ | __ $$ | __ $$    $$ |$$ |  $$/       #
#       $$ |  $$ \__$$ |$$ |      $$ | $$ | $$ |/$$$$$$$ |  $$ |/  |$$ |/  |$$$$$$$$/ $$ |            #
#       $$ |  $$    $$/ $$ |      $$ | $$ | $$ |$$    $$ |  $$  $$/ $$  $$/ $$       |$$ |            #
#  ______$______$______ ______ ______ ______$______$______ ______/______$______$______$______ ______  #
# /      /      /      /      /      /      /      /      /      /      /      /      /      /      | #
# $$$$$$/$$$$$$/$$$$$$/$$$$$$/$$$$$$/$$$$$$/$$$$$$/$$$$$$/$$$$$$/$$$$$$/$$$$$$/$$$$$$/$$$$$$/$$$$$$/  #
#Variables %player% and %money%
#Note %player% only works on Others
#When adding in an apostrophe ' do ''
Balance: '&aBalance:&7 $%money%'
Others: '&a%player%''s Balance:&7 $%money%'
#Should Balance Formatter shorten balances?
Shortener: true