#          _    _ _____   ____  _____              _____  _____   ____  ______ _____ _      ______ 
#     /\  | |  | |  __ \ / __ \|  __ \     /\     |  __ \|  __ \ / __ \|  ____|_   _| |    |  ____|
#    /  \ | |  | | |__) | |  | | |__) |   /  \    | |__) | |__) | |  | | |__    | | | |    | |__   
#   / /\ \| |  | |  _  /| |  | |  _  /   / /\ \   |  ___/|  _  /| |  | |  __|   | | | |    |  __|  
#  / ____ \ |__| | | \ \| |__| | | \ \  / ____ \  | |    | | \ \| |__| | |     _| |_| |____| |____ 
# /_/    \_\____/|_|  \_\\____/|_|  \_\/_/    \_\ |_|    |_|  \_\\____/|_|    |_____|______|______|
# PLugin de perfil simples e "completo", com suporte ao [PlaceholderAPI].
# Desenvolvido por dennermelo                                        

# Abaixo, você define a quantidade de slots para o inventário, sendo 27 = 3 barras, 45 = 5 barras, 54 = 6 barras;
SlotsInventario: 27

# Abaixo, você cria os itens de sua preferência, caso não saiba o Material para os itens do Minecraft, acesse:
# https://dev.bukkit.org/projects/supplies/pages/material-list
# Caso você não saiba as Placeholders, acesse:
# https://www.spigotmc.org/wiki/placeholderapi-placeholders/
# Ao setar o slot, lembre-se de colocar o número desejado - 1; exemplo: 9 = 9-1 = 8 <- Esse vai no Slot.
InventarioPerfil:
  item1:
    Material: ENDER_CHEST
    Display_Name: '&cEstatisticas | Sky Wars'
    Lore:
      - ''
      - '&eWins Solo: &f0'
      - '&eWins Dupla: &f0'
      - '&eGame Kills: &f0'
      - ''
    Slot: 10
  item2:
    Material: CHEST
    Display_Name: '&aEconomia | &f%player_name%'
    Lore:
      - ''
      - '&eDinheiro: &aR$%vault_eco_balance_formatted%'
      - ''
    Slot: 16
# Aqui você configura o que quer mostrar nas informações na cabeça.
HeadPerfil:
  Display_Name: '&ePlayer Info:'
  Lore:
    - ''
    - '&eNickname: &f%player_name%'
    - '&ePing: %player_ping%'
    - '&eIP: %player_ip%'
    - '&ePrimeiro Login: &f%player_first_join_date%'
    - ''
  Slot: 13