Configuracoes:
  Permissao-Necessaria-Admin: 'aurora.vertickets'

Mensagens:
  Sem-Permissao: '&c[Aurora Tickets] Sem permissão para isto.'
  Ticket-Nao-Encontrado: '&c[Aurora Tickets] Este Ticket não foi encontrada.'
  Usage-Ticket: '&c[Aurora Ticket] Utilize, /Ticket criar <Ticket>.'
  Usage-Ticket-Usuario: '&e[Aurora Tickets] Para criar um ticket, utilize: /ticket <mensagem>.'
  Ticket-Criado: '&a[Aurora Tickets] Ticket criada com sucesso.'
  Ticket-Removido: '&c[Aurora Tickets] Ticket removido com sucesso.'
  Ticket-Inexistente: '&c[Aurora Tickets] Este ticket não existe.'
  Ja-Contem-Ticket: '&c[Auora Tickets] Já existe um ticket criado.'